version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: ketech_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ketech
      POSTGRES_PASSWORD: ketech_password
      POSTGRES_DB: ketech_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
